theme/beevibrant/index_full.html
theme/beevibrant/templates/base.html
theme/beevibrant/templates/footer.html
theme/beevibrant/templates/header.html

- content natural language declaration,
- more meaningful alternative text for logo.

Website accessibility improvements

---

theme/beevibrant/static/css/main.css

remove capitalize property for headers

---

content/metadata/2020/event.yml
theme/beevibrant/index_full.html

According to my count it should be EuroSciPy number 13. At least last lear we claimed 12th already.

fix count, good luck!

---

content/metadata/2020/menu.yml
content/pages/2020/finaid.md

Add details about the financial aid

Add Financial Aid page

---

content/pages/2022/about.md

Add another "Dr."

---

content/metadata/2022/menu.yml
content/pages/2022/maintainers.md

add maintainers page

---

content/metadata/2022/menu.yml
content/pages/2022/info.md
content/pages/2022/program_menu.md
content/pages/2022/sponsors.md

This is a hack for mobile users to access the links under the submenu items

fix submenu on phone

---

content/metadata/2022/menu.yml
content/pages/2022/info.md
content/pages/2022/venue.md
pelicanconf.py

Adds info about Basel and the venue

feat/venue: information about the venue

---

content/pages/2022/about.md
content/pages/2022/sponsoring.md

update sponsorship info

---

content/pages/2022/maintainers.md

To confirm with: Jarrod Millman <jarrod.millman@gmail.com>

maintainers: SPEC session

---

content/pages/2022/maintainers.md

To confirm with chiin-rui rhozeta.io <chiin-rui@rhozeta.io>

maintainers: education session

---

content/metadata/2022/keynotes.yml
content/pages/2022/venue.md

refactor keynote links and venue page

---

content/pages/2023/program.md

requires approval of @msgomez06 first and then your review

WIP - re-organizing the tracks

---

content/pages/2023/program.md

I saw that the rendering is not working as expected.
I propose to make bold the main topic and use items for the list of examples/sub-topics.

FIX use single indentation in items

---

content/pages/2023/code_of_conduct.md
content/pages/2023/program.md

I'm adding "Call for Proposals" date and pretalx link.

MAINT Add CfP dates and pretalx link

---

content/metadata/2023/event.yml

I'm adding CfP announcement to the main page

MAINT Add CfP announcement to the main page

---

content/pages/2023/maintainers.md
content/pages/2023/sprint.md

@adrinjalali do you mind having a quick look at this please?

Update information about sprints

---

content/pages/2023/finaid.md

The finaid information with updated date. 
Still needs to add the url of new form

WIP finaid

---

content/pages/2023/sprint.md

Hello!
I am reaching out to you on behalf of the braindecode library to express our interest in organizing a brain decode code sprint during EuroScipy.
Braindecode is a scientific Python library focusing on decoding brain signals with deep learning. Our library has been built using mne-python, PyTorch, and Skorch.
Currently, we have identified some key objectives for the code sprint. These include the
1) restructuring of our documentation to make it more accessible for new users, as well as the
2) re-implementation and optimization of our data loaders.
3) re-establish a solid training structure for our library.

Adding braindecode sprint

---

content/metadata/2023/menu.yml
content/pages/2023/tickets.md

Adding the link to the registration page with information in the sidebar.
We need to discuss the details regarding the streaming access.

Add dedicated page for registration in the sidebar

---

content/pages/2023/about.md

Updating the organizing team as suggested in a previous meeting.

Update organizing team

---

content/pages/2023/program_menu.md
content/pages/2023/social_event.md

Add the social event page for 2023

add social event for 2023

---

content/pages/2023/schedule.md
theme/beevibrant/static/css/main.css
theme/beevibrant/static/css/responsive.css
theme/beevibrant/templates/base.html
theme/beevibrant/templates/schedule.html

This carefully navigates between checks for screen width and scrolling set by pretalx widget

hack around the schedule scrolling

---

content/pages/2023/code_of_conduct.md

Add Mojdeh Rastgoo in CoC committee

---

content/pages/2023/tickets.md

Removing part where we mentioned streaming access for 2023

remove streaming tickets from pricing

---

content/pages/2023/current_sponsors.md

Points to a specific page instead to home.

Update link for Zeiss

---

content/pages/2023/code_of_conduct.md

@code-of-kpp
@marenwestermann
@alessiamarcolini

coc-update

---

content/pages/2024/tickets.md

Added ticket prices

---

README.md
content/pages/2024/tickets.md

adds the tito widget,
changed the level of the headings to ```##``` and ```###``` because we are under a title

Add tito widget for ticket selling

---

content/metadata/2024/event.yml

Add announcement about ticket sale to the home page

add ticket sale to home page

---

content/pages/2024/finaid.md

Here is the PR for the finaid update in the website. I appreciate your comments before 23rd. Thanks

Finaid for EuroSciPy 2024

---

content/pages/2024/finaid.md

Another try to update the finaid page.

Add finaid for 2024

---

content/pages/2024/current_sponsors.md

Add NumFOCUS as finaid sponsor

Add NumFOCUS as finaid sponsor

---

content/pages/2024/sponsoring.md

We don't have any big sponsors yet. Extending the deadlines for sponsors seems very sensible. ;)

Extend sponsoring deadlines

---

content/metadata/2024/menu.yml
content/pages/2024/lightning_talks.md
content/pages/2024/program_menu.md

add lightning talks to the website

add lightning talks to the website

---

content/pages/index.md

Make 2025 the next edition

---

content/blog/new-website/contents.lr

Add blog post about new website

---

content/finaid/contents.lr

Make deadline dates consistent

---

content/blog/maintainers-track/contents.lr

Replaces https://github.com/euroscipy/euroscipy.github.io/pull/172
This is a blog post, not a new page

Add blog post Maintainers Track

---

content/faq/contents.lr
content/tickets/contents.lr
databags/links.json

this addresses free tickets for speakers

tickets for speakers

---

EuroSciPy.lektorproject
requirements.txt

All headers get an id and become links.

Add plugin lektor-markdown-header-anchors

---

content/sponsoring/contents.lr

Silver and Bronze sponsors were missing

Add missing sponsors

---

templates/schedule.html

the problem was that we had the schedule in the body. 
Thx to Tobias Kunze.

encapsulate schedule in a div

---

content/sprints/contents.lr

Add some info for napari sprint
